added batch file processing sample
dapr/samples pull request #11
Opened 2020-08-27 22:15 UTC by programaka

2020-09-05 00:00 UTC, orizohar requested changes

2020-09-05 00:00 UTC, orizohar commented on batch-file-processing/deployment.md
> +    ```
I recommend adding another sanity check here, to check the logs of the receiver and see it starts getting events from blobs being created
`kubectl logs deployment/batch-receiver -c batch-receiver`

2020-09-05 00:00 UTC, orizohar commented on batch-file-processing/deployment.md
> +6. Replace <storage_sas_token> in [batchProcessor/config.json](batchProcessor/config.json) with the SAS token that you generated earlier.
I'd add a note to make sure there is a "?" before the pasted SAS, this is where I had to troubleshoot

2020-09-10 23:53 UTC, orizohar commented
@programaka - can you address the comments in this PR?

@yaron2 to review as well

2020-09-13 03:19 UTC, programaka commented on batch-file-processing/deployment.md
> +## Set up Cluster
added the getting credentials step

2020-09-13 03:20 UTC, programaka commented on batch-file-processing/deployment.md
> +Run [this script](scripts/deploy_storage.ps1) to execute steps 1 through 4 or follow the steps below.
mentioned it in Scripts section

2020-09-13 03:20 UTC, programaka commented on batch-file-processing/deployment.md
> +8. To test, run:
added

2020-09-13 03:22 UTC, programaka commented on batch-file-processing/deployment.md
> +    * [deploy/batch-processor-keda.yaml](deploy/batch-processor-keda.yaml)
Removed batch-processor.yaml to avoid the confusion. batch-processor-keda needs to be deployed (it uses keda for scaling). We can add a version without keda if needed later.

2020-09-13 03:22 UTC, programaka commented on batch-file-processing/deployment.md
> +    ```
added 2 more steps

2020-09-13 03:24 UTC, programaka commented on batch-file-processing/deployment.md
> +    az aks create --resource-group <resource-group-name> --name <cluster-name> --node-count 2 --kubernetes-version 1.17.9 --enable-addons http_application_routing --generate-ssh-keys --location westu
fixed

2020-09-13 03:24 UTC, programaka commented on batch-file-processing/deployment.md
> +Run [this script](scripts/deploy_cosmosdb.ps1) to execute steps 1 through 4 or follow the steps below.
fixed

2020-09-13 03:25 UTC, programaka commented on batch-file-processing/deployment.md
> +6. Replace <storage_sas_token> in [batchProcessor/config.json](batchProcessor/config.json) with the SAS token that you generated earlier.
added a note

2020-09-13 03:30 UTC, programaka commented on batch-file-processing/deployment.md
> +        --location westus `
fixed in both deployment.md and scripts

2020-09-13 03:33 UTC, programaka commented
@orizohar  Hi Ori, thanks a lot for testing the deployment! I fixed all the issues that you mentioned.

2020-09-14 16:57 UTC, orizohar approved these changes

2020-09-14 17:09 UTC, merged