Sample/pluggable components
dapr/samples pull request #120
Opened 2022-10-06 19:00 UTC by mcandeia

Added .NET Template for Pluggable Components.

Issue: #119

2022-10-07 16:56 UTC, artursouza requested changes

2022-10-07 16:56 UTC, artursouza commented on pluggable-components-dotnet-template/Services/Services.cs
> +// Uncomment the lines below to implement the StateStore methods defined in the following protofiles
Please, uncomment and have the template to be useable from the beginning, even if the implementation is just logging the call.

2022-10-07 17:54 UTC, mcandeia commented on pluggable-components-dotnet-template/Services/Services.cs
> +// Uncomment the lines below to implement the StateStore methods defined in the following protofiles
My concern here is the user be confused about having to implement everything at once. Can we have another sample that is only for statestore for instance?

2022-10-07 18:16 UTC, johnewart commented on pluggable-components-dotnet-template/Services/Services.cs
> +// Uncomment the lines below to implement the StateStore methods defined in the following protofiles
Is this because the way daprd is using grace reflection and so if they are not commented out then the dapr daemon thinks this service provides extra functionality that it doesn't?

2022-10-07 22:42 UTC, mcandeia commented on pluggable-components-dotnet-template/Services/Services.cs
> +// Uncomment the lines below to implement the StateStore methods defined in the following protofiles
Basically, yes @johnewart

2022-10-07 22:46 UTC, msfussell commented on pluggable-components-dotnet-template/README.md
> +This is a template project and that contains the barebones to start work with Pluggable Components in .NET.
```suggestion
This is a template project that enables you to build a pluggable statestore component in .NET.
```

2022-10-07 22:48 UTC, msfussell commented on pluggable-components-dotnet-template/README.md
> +2. Examine the `./Services/Services.cs` file. You'll see four commented classes. They are `StateStoreService`, `PubSubService`, `InputBindingService` and `OutputBindingService`, their protos are defi
```suggestion
2. Examine the `./Services/Services.cs` file. You'll see four commented classes. They are `StateStoreService`, `PubSubService`, `InputBindingService` and `OutputBindingService`, their protos are defined inside `./Protos` folder. Uncomment any number of them as these serve as a unimplemented proto service that you start from.
```

2022-10-07 22:49 UTC, msfussell commented on pluggable-components-dotnet-template/README.md
> +### Step 2 - Register your Unimplemented Service
```suggestion
### Step 2 - Register your unimplemented service
```

2022-10-07 22:50 UTC, msfussell commented on pluggable-components-dotnet-template/README.md
> +Once you decide which of proto services you are going to implement, go to the `./Program.cs` file and exame the lines between 46-50 you'll see commented lines, uncomment based on the services that yo
```suggestion
Once you decide which of proto services you are going to implement, go to the `./Program.cs` file and examine the lines 46-50.  You'll see commented lines, uncomment based on the services that you chose to implement.
```

2022-10-11 21:03 UTC, msfussell approved these changes
LGTM

2022-10-12 05:30 UTC, artursouza approved these changes

2022-10-12 05:30 UTC, merged

2023-08-01 00:05 UTC, msfussell commented
Closing issue