Initial commit of twitter processing pipeline sample using python-sdk
dapr/samples pull request #37
Opened 2020-12-03 22:15 UTC by youngbupark

This is the initial commit of twitter processing pipeline sample using python-sdk.

Closes #36

2020-12-03 22:18 UTC, mchmarny commented on twitter-sentiment-processor/demos/py-demo/README.md
> +Twitter and azure cognitive servce credentials will have to set in a new file [local_secrets.json](./local_secrets.json):
**A**zure

2020-12-03 22:20 UTC, mchmarny commented on twitter-sentiment-processor/demos/py-demo/README.md
> +All the applications described here uses Spring Boot.
Spring Boot? I thought this was Python example?

2020-12-03 22:20 UTC, mchmarny commented on twitter-sentiment-processor/demos/py-demo/README.md
> +* Bindings - is used to receive Twitter feed as defined in [provider/components/twitter_binding.yaml](provider/components/twitter_binding.yaml)
Binding is or Bandings are

2020-12-03 22:21 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/README.md
> +Twitter and azure cognitive servce credentials will have to set in a new file [local_secrets.json](./local_secrets.json):
yup I copied from @artursouza 's example :) nice catch.

2020-12-03 22:21 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/README.md
> +All the applications described here uses Spring Boot.
yup I copied from @artursouza 's example :) nice catch.

2020-12-03 22:22 UTC, mchmarny commented on twitter-sentiment-processor/demos/py-demo/README.md
> +Viewer app is a Flask web application serving web service. [flask-SocketIO](https://flask-socketio.readthedocs.io/en/latest/) is used to enable real-time update tweets on the web page. This subscribe
creates subscription to the tweet topic?

2020-12-03 22:22 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/README.md
> +Twitter and azure cognitive servce credentials will have to set in a new file [local_secrets.json](./local_secrets.json):
done

2020-12-03 22:22 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/README.md
> +All the applications described here uses Spring Boot.
removed :)

2020-12-03 22:23 UTC, mchmarny commented on twitter-sentiment-processor/demos/py-demo/README.md
> +* Pub Sub - is used to subscribe tweets to show tweet sentiment on webpage. PubSub is defined in [provider/components/pubsub.yaml](viewer/components/pubsub.yaml)
is used to subscribe to the `tweets` topic so that they can be displayed on the tweet sentiment on webpage

2020-12-03 22:25 UTC, mchmarny requested changes
I can't speak to the Python code but the readme needs some more work. Please address the references to Spring Boot, Azure service names are inconsistencies, and general grammar issues.

2020-12-03 22:26 UTC, artursouza commented on twitter-sentiment-processor/demos/py-demo/processor/processor.py
> +COGNITIVE_SERVICE_API_DOMAIN = os.getenv('COGNITIVE_API_DOMAIN', 'tweet-sentiment-py')
No default here, just fail if empty. This endpoint belongs to each Azure account and is not shared.

2020-12-03 22:26 UTC, artursouza commented on twitter-sentiment-processor/demos/py-demo/provider/provider.py
> +        'sentiment': 0.5,
Is sentiment a number? Why the magic 0.5?

2020-12-03 22:26 UTC, artursouza commented on twitter-sentiment-processor/demos/py-demo/viewer/static/js/app.js
> +            var tmsg = "<img src='" + t.author_pic + "' class='profile-pic' />" +
Take a look at the Java demo since I handled a corner case here to avoid displaying 'undefined'.

2020-12-03 22:26 UTC, artursouza commented on twitter-sentiment-processor/demos/py-demo/viewer/templates/index.html
> +                <a href="https://github.com/mchmarny/dapr-demos">
This is not in his repo. Remove this. See how I did in the Java demo.

2020-12-03 22:26 UTC, artursouza commented on twitter-sentiment-processor/demos/py-demo/README.md
> +All the applications described here uses Spring Boot.
Not really, this is not Java :)

2020-12-03 22:26 UTC, artursouza commented on twitter-sentiment-processor/demos/py-demo/processor/processor.py
> +    response = client.analyze_sentiment(documents=[text], language=lang)[0]
There is not always a valid result, handle those cases. In the Java demo, I return it as 'unknown' sentiment and I added a svg in the UI to render that.

2020-12-03 22:26 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/README.md
> +Viewer app is a Flask web application serving web service. [flask-SocketIO](https://flask-socketio.readthedocs.io/en/latest/) is used to enable real-time update tweets on the web page. This subscribe
done

2020-12-03 22:27 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/provider/provider.py
> +        'sentiment': 0.5,
I got this number from the original `demo2`

2020-12-03 22:29 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/README.md
> +All the applications described here uses Spring Boot.
fixed. I took this readme from yours.

2020-12-03 22:29 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/processor/processor.py
> +    response = client.analyze_sentiment(documents=[text], language=lang)[0]
ok.

2020-12-03 23:06 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/viewer/templates/index.html
> +                <a href="https://github.com/mchmarny/dapr-demos">
fixed.

2020-12-03 23:07 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/viewer/static/js/app.js
> +            var tmsg = "<img src='" + t.author_pic + "' class='profile-pic' />" +
the demo2 code is a bit different from javademo code. unlike javademo, processor in python will refer user.name as a fallback of user.screen_name.

2020-12-03 23:10 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/processor/processor.py
> +    response = client.analyze_sentiment(documents=[text], language=lang)[0]
I added unknown svg and if cognitive service cannot process the particular lang, it returns 'unknown' sentiment.

2020-12-03 23:10 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/provider/provider.py
> +        'sentiment': 0.5,
removed.

2020-12-03 23:10 UTC, youngbupark commented on twitter-sentiment-processor/demos/py-demo/processor/processor.py
> +COGNITIVE_SERVICE_API_DOMAIN = os.getenv('COGNITIVE_API_DOMAIN', 'tweet-sentiment-py')
moved it to secret.

2020-12-04 00:29 UTC, youngbupark commented
> I can't speak to the Python code but the readme needs some more work. Please address the references to Spring Boot, Azure service names are inconsistencies, and general grammar issues.

Thanks for the review :) I fixed all comments. initially, I ported your [pipeline demo](https://github.com/mchmarny/dapr-demos/tree/master/pipeline) and then realized that sample pipeline app is different from your repo's one. 

Anyhow, this is really good sample app :)

2020-12-04 19:50 UTC, artursouza approved these changes

2020-12-05 02:14 UTC, merged