Use MS Build of OpenJDK
dapr/samples pull request #61
Opened 2021-04-28 19:51 UTC by brunoborges

Hey @DarqueWarrior @artursouza, here's an update to use the MS Build of OpenJDK.

2021-04-29 05:07 UTC, artursouza requested changes
Thanks for the contribution. I just have a question about the base image.

2021-04-29 05:07 UTC, artursouza commented on twitter-sentiment-processor/demos/javademo/processor/Dockerfile
> +FROM ubuntu:20.04
Is there a distroless base?

2021-04-29 05:07 UTC, artursouza commented on twitter-sentiment-processor/demos/javademo/processor/Dockerfile
> +RUN apt-get update && \
Does MS plan to offer a distroless base image with the JDK pre installed, similar to the one we use from g?

2021-04-29 05:07 UTC, artursouza commented on twitter-sentiment-processor/demos/javademo/provider/Dockerfile
> +FROM ubuntu:20.04
Same.

2021-04-29 05:07 UTC, artursouza commented on twitter-sentiment-processor/demos/javademo/viewer/Dockerfile
> +FROM ubuntu:20.04
Same.

2021-04-29 17:35 UTC, brunoborges commented on twitter-sentiment-processor/demos/javademo/processor/Dockerfile
> +FROM ubuntu:20.04
Not at the moment.

2021-04-29 17:35 UTC, brunoborges commented on twitter-sentiment-processor/demos/javademo/processor/Dockerfile
> +RUN apt-get update && \
We are in the process of defining our container image deliverables. In the short term, we will not be publishing a distroless image.

2021-05-04 05:24 UTC, artursouza approved these changes

2021-05-04 05:24 UTC, merged